# Generated by Django 2.2.2 on 2019-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=10)),
                ('dateofbirth', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('skills', models.CharField(max_length=200)),
                ('total_experience', models.CharField(max_length=100)),
                ('realtime_experience', models.CharField(max_length=100)),
                ('current_ctc', models.CharField(max_length=10)),
                ('expected_ctc', models.CharField(max_length=10)),
                ('noticeperiod', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
